services:
  web:
    build: .
    command: gunicorn tutoriel.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: budget
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: corporate2019
