# Generated by Django 5.1 on 2024-10-09 00:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ligneboncommande',
            name='idannee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tutorial.annee'),
        ),
        migrations.AddField(
            model_name='ligneboncommande',
            name='idoperation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tutorial.operation'),
        ),
    ]
