# Generated by Django 5.1 on 2024-09-03 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0002_sousprogramme_remove_programme_idaxestrategique_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tache',
            old_name='libelle',
            new_name='libelleindicateur',
        ),
        migrations.AddField(
            model_name='tache',
            name='libelleobjectif',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
