# Generated by Django 5.1 on 2024-09-06 03:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0003_rename_libelle_tache_libelleindicateur_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operation',
            name='idnature_t',
        ),
        migrations.RemoveField(
            model_name='operation',
            name='periode_id',
        ),
        migrations.AddField(
            model_name='operation',
            name='idsourcefinancement',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tutorial.sourcefinacement'),
        ),
        migrations.AddField(
            model_name='operation',
            name='idsousprogramme',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tutorial.sousprogramme'),
        ),
        migrations.AlterField(
            model_name='operation',
            name='idtache',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tutorial.tache'),
        ),
    ]
