# Generated by Django 5.1 on 2024-09-07 23:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0004_remove_operation_idnature_t_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='elementcout',
            name='idimputation',
        ),
        migrations.RemoveField(
            model_name='elementcout',
            name='idunite',
        ),
        migrations.RemoveField(
            model_name='structure',
            name='idadresse',
        ),
        migrations.RemoveField(
            model_name='structure',
            name='idarrondissement',
        ),
        migrations.RemoveField(
            model_name='structure',
            name='iddepartement',
        ),
        migrations.RemoveField(
            model_name='structure',
            name='idniveaupyramide',
        ),
        migrations.RemoveField(
            model_name='structure',
            name='idpyramide',
        ),
        migrations.RemoveField(
            model_name='structure',
            name='idrattachement',
        ),
        migrations.RemoveField(
            model_name='structure',
            name='idregion',
        ),
        migrations.RemoveField(
            model_name='structure',
            name='idstatutstructure',
        ),
        migrations.RemoveField(
            model_name='structure',
            name='idtypestructure',
        ),
        migrations.AlterField(
            model_name='elementcout',
            name='idsousrubriquemercurial',
            field=models.ForeignKey(blank=True, db_column='idsousrubriquemercurial', null=True, on_delete=django.db.models.deletion.CASCADE, to='tutorial.sousrubrique'),
        ),
    ]
