# Generated by Django 5.1 on 2024-09-08 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0006_alter_elementcout_idrubriquemercurial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
