# Generated by Django 5.1 on 2024-09-08 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0007_ir_tva'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='nom',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
