# Generated by Django 5.1 on 2024-09-08 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0008_article_nom'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paragraphe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255, null=True)),
                ('idarticle', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tutorial.article')),
                ('idsection', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tutorial.section')),
            ],
        ),
    ]
