# Generated by Django 5.1 on 2024-09-08 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0009_paragraphe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boncommande',
            name='idbudget',
        ),
        migrations.RemoveField(
            model_name='boncommande',
            name='idimputation',
        ),
        migrations.RemoveField(
            model_name='boncommande',
            name='idmoyens',
        ),
        migrations.RemoveField(
            model_name='boncommande',
            name='idsignataire',
        ),
        migrations.AddField(
            model_name='boncommande',
            name='idactivite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tutorial.activite'),
        ),
        migrations.AddField(
            model_name='boncommande',
            name='idir',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tutorial.ir'),
        ),
        migrations.AddField(
            model_name='boncommande',
            name='idoperation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tutorial.operation'),
        ),
        migrations.AddField(
            model_name='boncommande',
            name='idparagraphe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tutorial.paragraphe'),
        ),
        migrations.AddField(
            model_name='boncommande',
            name='idsousprogramme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tutorial.sousprogramme'),
        ),
        migrations.AddField(
            model_name='boncommande',
            name='idtache',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tutorial.tache'),
        ),
        migrations.AddField(
            model_name='boncommande',
            name='idtva',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tutorial.tva'),
        ),
    ]
