# Generated by Django 5.1 on 2024-09-10 07:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0010_remove_boncommande_idbudget_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='typefinancement',
            name='idnaturetache',
        ),
        migrations.AddField(
            model_name='naturetache',
            name='idtypefinancement',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tutorial.typefinancement'),
        ),
    ]
