# Generated by Django 5.1 on 2024-09-12 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0014_alter_operation_idparagraphe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operation',
            name='idannee',
        ),
        migrations.AddField(
            model_name='operation',
            name='idannee',
            field=models.ManyToManyField(related_name='operations', to='tutorial.annee'),
        ),
    ]
