# Generated by Django 5.1 on 2024-09-12 03:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0015_remove_operation_idannee_operation_idannee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operation',
            name='idannee',
        ),
        migrations.RemoveField(
            model_name='operation',
            name='idparagraphe',
        ),
        migrations.CreateModel(
            name='OperationDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('idannee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tutorial.annee')),
                ('idoperation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tutorial.operation')),
            ],
        ),
    ]
