# Generated by Django 5.1 on 2024-09-12 03:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0016_remove_operation_idannee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='operationdetail',
            name='idparagraphe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tutorial.paragraphe'),
        ),
    ]
