# Generated by Django 5.1 on 2024-09-12 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0017_operationdetail_idparagraphe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operationdetail',
            name='montant',
            field=models.IntegerField(null=True),
        ),
    ]
