# Generated by Django 5.1 on 2024-09-12 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0018_alter_operationdetail_montant'),
    ]

    operations = [
        migrations.AddField(
            model_name='societe',
            name='boite_postale',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='societe',
            name='cnps_number',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='societe',
            name='contribuable',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='societe',
            name='localisation',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='societe',
            name='registre',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
