# Generated by Django 5.1 on 2024-09-13 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0019_societe_boite_postale_societe_cnps_number_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='utilisateur',
            old_name='cni',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='utilisateur',
            old_name='etat',
            new_name='password',
        ),
        migrations.RemoveField(
            model_name='utilisateur',
            name='idadresse',
        ),
        migrations.RemoveField(
            model_name='utilisateur',
            name='idarrondissement',
        ),
        migrations.RemoveField(
            model_name='utilisateur',
            name='idpays',
        ),
        migrations.RemoveField(
            model_name='utilisateur',
            name='idstatut_matrimonial',
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='photo',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='sexe',
            field=models.IntegerField(max_length=255, null=True),
        ),
    ]
