# Generated by Django 5.1 on 2024-09-13 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0020_rename_cni_utilisateur_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='telephone',
            field=models.IntegerField(null=True),
        ),
    ]
