# Generated by Django 5.1 on 2024-09-14 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0021_utilisateur_telephone'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
