# Generated by Django 5.1 on 2024-09-14 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0023_annee_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='sousprogramme',
            name='code',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
