# Generated by Django 5.1 on 2024-09-14 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0024_sousprogramme_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='activite',
            name='code',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='paragraphe',
            name='code',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
