# Generated by Django 5.1 on 2024-09-14 23:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0025_activite_code_paragraphe_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='institution',
            name='date_enregistre',
        ),
        migrations.RemoveField(
            model_name='institution',
            name='derniere_modif',
        ),
        migrations.CreateModel(
            name='OperationDetailMontant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant_global', models.IntegerField(null=True)),
                ('idoperation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tutorial.operation')),
            ],
        ),
    ]
