# Generated by Django 5.1 on 2024-09-15 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0026_remove_institution_date_enregistre_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operationdetailmontant',
            name='idoperation',
        ),
        migrations.DeleteModel(
            name='OperationDetail',
        ),
        migrations.DeleteModel(
            name='OperationDetailMontant',
        ),
    ]
