# Generated by Django 5.1 on 2024-09-15 00:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0027_remove_operationdetailmontant_idoperation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperationDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.IntegerField(null=True)),
                ('idannee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tutorial.annee')),
                ('idoperation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tutorial.operation')),
                ('idparagraphe', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tutorial.paragraphe')),
            ],
        ),
        migrations.CreateModel(
            name='OperationDetailMontant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant_global', models.IntegerField(null=True)),
                ('idoperation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tutorial.operation')),
            ],
            options={
                'db_table': 'operationdetailmontant',
            },
        ),
    ]
