# Generated by Django 5.1 on 2024-09-15 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0028_operationdetail_operationdetailmontant'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OperationDetailMontant',
        ),
    ]
