# Generated by Django 5.1 on 2024-09-15 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0029_delete_operationdetailmontant'),
    ]

    operations = [
        migrations.RenameField(
            model_name='structure',
            old_name='article',
            new_name='code',
        ),
        migrations.RenameField(
            model_name='structure',
            old_name='nomrespo',
            new_name='sigle',
        ),
    ]
