# Generated by Django 5.1 on 2024-09-16 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0030_rename_article_structure_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='departement',
            name='date_enregistre',
        ),
        migrations.RemoveField(
            model_name='departement',
            name='derniere_modif',
        ),
        migrations.RemoveField(
            model_name='exercise_action',
            name='derniere_modif',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='date_enregistre',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='derniere_modif',
        ),
        migrations.RemoveField(
            model_name='revue',
            name='etat',
        ),
        migrations.RemoveField(
            model_name='revue',
            name='nom',
        ),
        migrations.RemoveField(
            model_name='revuedifficilte',
            name='date_enregistre',
        ),
        migrations.RemoveField(
            model_name='revuedifficilte',
            name='derniere_modif',
        ),
        migrations.RemoveField(
            model_name='revueperformance',
            name='date_enregistre',
        ),
        migrations.RemoveField(
            model_name='revueperformance',
            name='derniere_modif',
        ),
        migrations.RemoveField(
            model_name='verifiaction_op',
            name='date_verification',
        ),
    ]
