# Generated by Django 5.1 on 2024-09-19 17:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0031_remove_departement_date_enregistre_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boncommande',
            name='idactivite',
        ),
        migrations.RemoveField(
            model_name='boncommande',
            name='idoperation',
        ),
        migrations.RemoveField(
            model_name='boncommande',
            name='idparagraphe',
        ),
        migrations.RemoveField(
            model_name='boncommande',
            name='idsociete',
        ),
        migrations.RemoveField(
            model_name='boncommande',
            name='idsousprogramme',
        ),
        migrations.RemoveField(
            model_name='boncommande',
            name='idstructure',
        ),
        migrations.RemoveField(
            model_name='boncommande',
            name='idtache',
        ),
        migrations.CreateModel(
            name='DetailBonCommande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idactivite', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tutorial.activite')),
                ('idboncommande', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tutorial.boncommande')),
                ('idoperation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tutorial.operation')),
                ('idparagraphe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tutorial.paragraphe')),
                ('idsociete', models.ForeignKey(blank=True, db_column='idsociete', null=True, on_delete=django.db.models.deletion.CASCADE, to='tutorial.societe')),
                ('idsousprogramme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tutorial.sousprogramme')),
                ('idstructure', models.ForeignKey(blank=True, db_column='idstructure', null=True, on_delete=django.db.models.deletion.CASCADE, to='tutorial.structure')),
                ('idtache', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tutorial.tache')),
            ],
        ),
    ]
