# Generated by Django 5.1 on 2024-09-19 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0032_remove_boncommande_idactivite_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='boncommande',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
