# Generated by Django 5.1 on 2024-09-24 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0033_boncommande_status'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='detailboncommande',
            table='detailboncommande',
        ),
    ]
