# Generated by Django 5.1 on 2024-09-25 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0034_alter_detailboncommande_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boncommande',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
