# Generated by Django 5.1 on 2024-09-26 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0037_boncommande_idinstitution_boncommande_idsociete'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detailboncommande',
            name='idsociete',
        ),
    ]
