# Generated by Django 5.1 on 2024-09-26 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0038_remove_detailboncommande_idsociete'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='grade',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='matricule',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
