# Generated by Django 5.1 on 2024-09-26 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0039_utilisateur_grade_utilisateur_matricule'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='idrole',
            field=models.ManyToManyField(null=True, to='tutorial.role'),
        ),
    ]
