# Generated by Django 5.1 on 2024-09-26 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0040_role_utilisateur_idrole'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='nom',
            field=models.CharField(choices=[('SA', 'SuperAdministrateur'), ('A', 'Administrateur'), ('SU', 'Simple Utilisateur')], max_length=255, null=True),
        ),
    ]
