# Generated by Django 5.1 on 2024-09-26 21:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0041_alter_role_nom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ligneboncommande',
            name='total',
            field=models.IntegerField(null=True),
        ),
        migrations.CreateModel(
            name='Decision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=255, null=True)),
                ('date', models.DateField(null=True)),
                ('objet', models.CharField(max_length=255, null=True)),
                ('montant', models.CharField(null=True)),
                ('iduser', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tutorial.utilisateur')),
            ],
        ),
    ]
