# Generated by Django 5.1 on 2024-09-26 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0042_alter_ligneboncommande_total_decision'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ligneboncommande',
            name='total',
            field=models.FloatField(null=True),
        ),
    ]
