# Generated by Django 5.1 on 2024-09-26 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0043_alter_ligneboncommande_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ligneboncommande',
            name='total',
            field=models.IntegerField(null=True),
        ),
    ]
