# Generated by Django 5.1 on 2024-09-28 10:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0044_alter_ligneboncommande_total'),
    ]

    operations = [
        migrations.CreateModel(
            name='Procedure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=255, null=True)),
                ('objet', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='signataire',
            old_name='adresse',
            new_name='code',
        ),
        migrations.RenameField(
            model_name='signataire',
            old_name='nom',
            new_name='libelle',
        ),
        migrations.RemoveField(
            model_name='signataire',
            name='idstructure',
        ),
        migrations.RemoveField(
            model_name='signataire',
            name='prenom',
        ),
        migrations.RemoveField(
            model_name='signataire',
            name='telephone',
        ),
        migrations.AlterModelTable(
            name='signataire',
            table=None,
        ),
        migrations.CreateModel(
            name='LettreCommande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=255, null=True)),
                ('status', models.IntegerField(default=0)),
                ('idactivite', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tutorial.activite')),
                ('idinstitution', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tutorial.institution')),
                ('idir', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tutorial.ir')),
                ('idoperation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tutorial.operation')),
                ('idparagraphe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tutorial.paragraphe')),
                ('idsociete', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tutorial.societe')),
                ('idsousprogramme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tutorial.sousprogramme')),
                ('idstructure', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tutorial.structure')),
                ('idtache', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tutorial.tache')),
                ('idtva', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tutorial.tva')),
                ('idprocedure', models.ForeignKey(max_length=255, null=True, on_delete=django.db.models.deletion.CASCADE, to='tutorial.procedure')),
            ],
        ),
    ]
