# Generated by Django 5.1 on 2024-09-28 12:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0045_procedure_rename_adresse_signataire_code_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lettrecommande',
            old_name='numero',
            new_name='numero_lettre',
        ),
        migrations.RemoveField(
            model_name='lettrecommande',
            name='idactivite',
        ),
        migrations.RemoveField(
            model_name='lettrecommande',
            name='idoperation',
        ),
        migrations.RemoveField(
            model_name='lettrecommande',
            name='idparagraphe',
        ),
        migrations.RemoveField(
            model_name='lettrecommande',
            name='idprocedure',
        ),
        migrations.RemoveField(
            model_name='lettrecommande',
            name='idsousprogramme',
        ),
        migrations.RemoveField(
            model_name='lettrecommande',
            name='idstructure',
        ),
        migrations.RemoveField(
            model_name='lettrecommande',
            name='idtache',
        ),
        migrations.CreateModel(
            name='DetailLettreCommande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idactivite', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tutorial.activite')),
                ('idlettrecommande', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tutorial.lettrecommande')),
                ('idoperation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tutorial.operation')),
                ('idparagraphe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tutorial.paragraphe')),
                ('idprocedure', models.ForeignKey(max_length=255, null=True, on_delete=django.db.models.deletion.CASCADE, to='tutorial.procedure')),
                ('idsousprogramme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tutorial.sousprogramme')),
                ('idstructure', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tutorial.structure')),
                ('idtache', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tutorial.tache')),
            ],
        ),
    ]
