# Generated by Django 5.1 on 2024-10-02 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0046_rename_numero_lettrecommande_numero_lettre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tache',
            name='code',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
