# Generated by Django 5.1 on 2024-10-02 22:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0047_tache_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='idannee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tutorial.annee'),
        ),
    ]
