# Generated by Django 5.1 on 2024-10-02 23:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0050_rename_numero_lettre_ordonancement_numero_ordonancement'),
    ]

    operations = [
        migrations.RenameField(
            model_name='decision',
            old_name='numero',
            new_name='numero_decision',
        ),
        migrations.RemoveField(
            model_name='decision',
            name='date',
        ),
        migrations.RemoveField(
            model_name='decision',
            name='iduser',
        ),
        migrations.RemoveField(
            model_name='decision',
            name='montant',
        ),
        migrations.RemoveField(
            model_name='decision',
            name='objet',
        ),
        migrations.AddField(
            model_name='decision',
            name='idinstitution',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tutorial.institution'),
        ),
        migrations.AddField(
            model_name='decision',
            name='idir',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tutorial.ir'),
        ),
        migrations.AddField(
            model_name='decision',
            name='idsociete',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tutorial.societe'),
        ),
        migrations.AddField(
            model_name='decision',
            name='idtva',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tutorial.tva'),
        ),
        migrations.AddField(
            model_name='decision',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
