# Generated by Django 5.1 on 2024-10-03 00:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0051_rename_numero_decision_numero_decision_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marche',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_marche', models.CharField(max_length=255, null=True)),
                ('status', models.IntegerField(default=0)),
                ('idinstitution', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tutorial.institution')),
                ('idir', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tutorial.ir')),
                ('idsociete', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tutorial.societe')),
                ('idtva', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tutorial.tva')),
            ],
        ),
    ]
