# Generated by Django 5.1 on 2024-10-03 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0053_lignelettrecommande'),
    ]

    operations = [
        migrations.AddField(
            model_name='operationdetail',
            name='montant_engage',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='operationdetail',
            name='montant_liquide',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='operationdetail',
            name='montant_valide',
            field=models.IntegerField(null=True),
        ),
    ]
