# Generated by Django 5.1 on 2024-10-03 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0054_operationdetail_montant_engage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='operationdetail',
            name='montant_restant',
            field=models.IntegerField(null=True),
        ),
    ]
