# Generated by Django 5.1 on 2024-10-03 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0055_operationdetail_montant_restant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operationdetail',
            name='montant_engage',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='operationdetail',
            name='montant_liquide',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='operationdetail',
            name='montant_restant',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='operationdetail',
            name='montant_valide',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
