# Generated by Django 5.1 on 2024-10-03 23:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0057_rename_idlettrecommande_detailordonancement_idordonancement_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LigneOrdonancement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prixunitaire', models.CharField(max_length=255, null=True)),
                ('quantite', models.CharField(max_length=255, null=True)),
                ('total', models.IntegerField(null=True)),
                ('prixmercurial', models.CharField(max_length=255, null=True)),
                ('verif', models.CharField(max_length=255, null=True)),
                ('references', models.CharField(max_length=255, null=True)),
                ('idelementcout', models.ForeignKey(blank=True, db_column='idelementcout', null=True, on_delete=django.db.models.deletion.CASCADE, to='tutorial.elementcout')),
                ('idordonancement', models.ForeignKey(blank=True, db_column='idboncommande', null=True, on_delete=django.db.models.deletion.CASCADE, to='tutorial.ordonancement')),
            ],
            options={
                'db_table': 'ligneordonancement',
            },
        ),
    ]
