# Generated by Django 5.1 on 2024-10-05 19:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0059_remove_ligneordonancement_idelementcout_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signataire',
            old_name='code',
            new_name='adresse',
        ),
        migrations.RenameField(
            model_name='signataire',
            old_name='libelle',
            new_name='nom',
        ),
        migrations.AddField(
            model_name='signataire',
            name='idstructure',
            field=models.ForeignKey(blank=True, db_column='idstructure', null=True, on_delete=django.db.models.deletion.CASCADE, to='tutorial.structure'),
        ),
        migrations.AddField(
            model_name='signataire',
            name='prenom',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='signataire',
            name='telephone',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterModelTable(
            name='signataire',
            table='signataire',
        ),
    ]
