# Generated by Django 5.1 on 2024-10-05 21:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0061_detaildecision'),
    ]

    operations = [
        migrations.CreateModel(
            name='LigneDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prixunitaire', models.CharField(max_length=255, null=True)),
                ('quantite', models.CharField(max_length=255, null=True)),
                ('total', models.IntegerField(null=True)),
                ('prixmercurial', models.CharField(max_length=255, null=True)),
                ('verif', models.CharField(max_length=255, null=True)),
                ('iddecision', models.ForeignKey(blank=True, db_column='idboncommande', null=True, on_delete=django.db.models.deletion.CASCADE, to='tutorial.decision')),
            ],
            options={
                'db_table': 'lignedecision',
            },
        ),
    ]
