# Generated by Django 5.1 on 2024-10-06 01:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0064_lignemarche'),
    ]

    operations = [
        migrations.AddField(
            model_name='lignemarche',
            name='idelementcout',
            field=models.ForeignKey(blank=True, db_column='idelementcout', null=True, on_delete=django.db.models.deletion.CASCADE, to='tutorial.elementcout'),
        ),
        migrations.AddField(
            model_name='lignemarche',
            name='references',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterModelTable(
            name='lignemarche',
            table=None,
        ),
    ]
