# Generated by Django 5.1 on 2024-10-06 22:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0065_lignemarche_idelementcout_lignemarche_references_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='boncommande',
            name='idprocedure',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tutorial.procedure'),
        ),
    ]
