# Generated by Django 5.1 on 2024-10-06 22:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0069_decision_idprocedure'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detailordonancement',
            name='idprocedure',
        ),
        migrations.AddField(
            model_name='marche',
            name='idprocedure',
            field=models.ForeignKey(max_length=255, null=True, on_delete=django.db.models.deletion.CASCADE, to='tutorial.procedure'),
        ),
    ]
