# Generated by Django 5.1 on 2024-10-06 23:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0072_lettrecommande_idsignataire'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordonancement',
            name='idsignataire',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tutorial.signataire'),
        ),
    ]
