# Generated by Django 4.2.16 on 2024-10-08 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0074_decision_idsignataire_marche_idsignataire'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utilisateur',
            name='idrole',
        ),
        migrations.DeleteModel(
            name='Role',
        ),
    ]
